### ISSUE TITLE
A little difference in shufflenetV2

### ISSUE THREAD

**Issue by DOGEwbx** [weiaicunzai/pytorch-cifar100#22]
In the original paper, there is a maxpool layer in 'pre' block between image and stage2 while I can't find it in this code.

**Comment by weiaicunzai** [comment]
I did not add this maxpooling layer, since more  pooling layers could cause  information loss during downsampling, therefore decrease the accuracy, and our data are 32x32 size images, do not suit for multiple downsample operations. You could add this maxpooling layer yourself, and see how the accuracy goes compare with my implementation.
