### ISSUE TITLE
Maybe some wrong in Xception

### ISSUE THREAD

**Issue by linqinghong** [weiaicunzai/pytorch-cifar100#6]
Hi,thanks for your nice job!

when i study the xception,i reading the paper and compare your implementation.
in your model/xception/SeperableConv2d, i get some confusion about:

in the paper,the author tell us that xception first through the 1x1 conv, but in your imple, you using depthwise first which is not 1x1 conv right? 
![image](https://user-images.githubusercontent.com/38312060/58062178-f3b72180-7bab-11e9-98aa-dd325f090298.png)
```
    def forward(self, x):
        x = self.depthwise(x)
        x = self.pointwise(x)

        return x
```

**Comment by jiangtaoo2333** [comment]
i'm afraid this depthwise conv is also wrong.

**Comment by weiaicunzai** [comment]
The order doesn't matter, you could see the paper:
"We argue that the first difference is unimportant, in par-ticular because these operations are meant to be used in astacked setting."


and other implmentations:
such as : 
https://github.com/jfzhang95/pytorch-deeplab-xception/blob/master/modeling/backbone/xception.py
https://github.com/tstandley/Xception-PyTorch/blob/master/xception.py
